export const EVENTS = {
  MENU_CREATED: "MENU_CREATED",
  MENU_UPDATED: "MENU_UPDATED",
  MENU_DELETED: "MENU_DELETED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_ENRICHED: "ORDER_ENRICHED",
  ORDER_FAILED: "ORDER_FAILED",
};
export const EVENT_CHANNEL = "MENU_EVENTS";
