export const EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_ENRICHED: "ORDER_ENRICHED",
  ORDER_FAILED: "ORDER_FAILED",
  TABLE_OCCUPY_REQUESTED: "TABLE_OCCUPY_REQUESTED",
  TABLE_OCCUPIED: "TABLE_OCCUPIED",
  TABLE_OCCUPY_FAILED: "TABLE_OCCUPY_FAILED",
  TABLE_RELEASE_REQUESTED: "TABLE_RELEASE_REQUESTED",
};

export const EVENT_CHANNEL = "ORDER_EVENTS";
